### ISSUE TITLE
Checks Information

### ISSUE THREAD

**Issue by patrickgroth** [amosproj/amos-ss2021-is-project-linter#60]
## User story
1. As a product owner
2. I need to specify the severity level, error message and category of the checks
3. So that the right information is displayed in the frontend

## Acceptance criteria
* Wiki page extended by additional column "severity level" an "error message"
* Wiki page filled by the product owners
* Information implemented in the configuration file

## Definition of done
* Reviewed by the release manager
* Approved by product owners

**Comment by lukasbm** [comment]
@patrickgroth  Are you sure, we want to hardcode the severity level in the Wiki pages?
I think severity is one of the things we want to have each user customize themselfes
