### ISSUE TITLE
Service Desk Deactivation

### ISSUE THREAD

**Issue by karri2909** [amosproj/amos-ss2021-is-project-linter#64]
## User story
1. As a backend developer
2. I need to check whether service desk is activated or deactivated and store the result in the database
3. So that front end can display the following Info message "There is no service desk in the project as users are expected to resolve issues by themselves"

## Acceptance criteria
- Test whether the result of the check is stored in the database.
- Link from frontend to api -> Test whether the info message is displayed if the service desk is activated

## Definition of done
- Code coverage of 50%
- Code review by release manager
- Approved by product owner

**Comment by zokto** [comment]
Implemented and tested in [commit](https://github.com/amosproj/amos-ss2021-is-project-linter/commit/74d37897dfc611ec21d10ac97eb0d050c85a665a)
