### ISSUE TITLE
Check - Default README.md file

### ISSUE THREAD

**Issue by karri2909** [amosproj/amos-ss2021-is-project-linter#66]
## User story
1. As a backend developer
2. I need to compare README.md file with the default README.md file and store the result in the database 
3. So that the front end can display the following info message "README.md file should not be default README.md file, 
    when the README.md file is same as default README.md file
 
## Acceptance criteria
- Test whether the result of the check is stored in the database.
- Link from frontend to api -> Test whether the info message is displayed when README.md file is same as default README.md 
   file

## Definition of done
- Code coverage of 50%
- Code review by release manager
- Approved by product owner

**Comment by zokto** [comment]
Implemented and tested in [commit](https://github.com/amosproj/amos-ss2021-is-project-linter/commit/52620b4a9d4dab79aad60a17628ee318eca5da34)
