### ISSUE TITLE
crawler

### ISSUE THREAD

**Issue by patrickgroth** [amosproj/amos-ss2021-is-project-linter#7]
## User story
1. As a developer
2. I need a crawler
3. So that I can check the repository from the front end for criteria being defined later.

## Acceptance criteria
* Crawler that gets a repository as link
* Performs predefined tests on the repository returned by the rest api
* Extendable with checks later on
* Returns the results of the checks to the frontend
* ...

## Definition of done
* Code reviewed by Lukas
* Acceptance criteria met
* Approved by product owner

**Comment by lukasbm** [comment]
We misunderstood the requirement. 
It was a lot easier in reality, because we offload all the work to the Linter.
