### ISSUE TITLE
Automate Tests (Github Actions)

### ISSUE THREAD

**Issue by nico-628** [amosproj/amos-ss2021-is-project-linter#8]
## User story
1. As a Developer
2. I want an automated testing environment
3. So that I can quickly get an overview over the project

## Acceptance criteria
* Automated Tests
* gitlab token is added
* automatically building docker images from artifacts and pushing them

## Definition of done
* Correctly executes all tests

**Comment by lukasbm** [comment]
Basically works now, but we can/should add caching to speed it up
