### ISSUE TITLE
Start Crawler API bug

### ISSUE THREAD

**Issue by lukasbm** [amosproj/amos-ss2021-is-project-linter#80]
## Bug Report
1. I found a bug in API
2. The following does not work: Endpoint `POST - /crawler` does not return. and takes endlessly time 
3. We need to return something to fix it

**Comment by zokto** [comment]
Fixed in [this](https://github.com/amosproj/amos-ss2021-is-project-linter/commit/266cdad6c568cbacfb1d23fab2496d62fba93f78) commit
