### ISSUE TITLE
hasSquashingEnabled issue

### ISSUE THREAD

**Issue by zokto** [amosproj/amos-ss2021-is-project-linter#83]
## Bug Report
1. I found a bug in backend
2. The following does not work: `hasSquashingEnabled` check in `CheckGitlabSettings.java`
3. We need to disable it temporarily until the API is updated. (find a way to query the api without creating a new branch or make sure all repositories allow the crawler to send merge requests/create new branches to fix it)

**Comment by Auron2402** [comment]
waiting for completetion of gitlab issue https://gitlab.com/gitlab-org/gitlab/-/issues/261458
